Repository maitrinh33/mobile-app_inner-mind, pull requests merged in 2025-06, with the labels that each got.

#15 feat(forum): implement forum screen and layout
  app/src/main/java/com/miu/meditationapp/models/ChatMessage.kt
  app/src/main/java/com/miu/meditationapp/models/PostHistory.kt
  app/src/main/java/com/miu/meditationapp/ui/main/ForumFragment.kt
  app/src/main/res/layout/activity_forum_new_post.xml
  app/src/main/res/layout/chat_from_row.xml
  app/src/main/res/layout/chat_to_row.xml
  app/src/main/res/layout/fragment_forum.xml
  app/src/main/res/layout/latest_message_row.xml
  app/src/main/res/layout/post_history_items.xml
  app/src/main/res/layout/post_history_items_received.xml
  app/src/main/res/layout/post_history_items_sent.xml
  app/src/main/res/layout/user_row_new_message.xml
Labels: enhancement

#17 feat(breath-exercise):add new screen for breath-exercise
  app/src/main/java/com/miu/meditationapp/BreathActivity.kt
  app/src/main/res/layout/activity_breath.xml
Labels: enhancement

#18 feat(Menditition): feature mendition activity and screen
  app/src/main/java/com/miu/meditationapp/MeditationActivity.kt
  app/src/main/res/layout/activity_meditation.xml
Labels: enhancement

#19 feat/screen: implement video learnings
  app/src/main/java/com/miu/meditationapp/ui/main/LearnFragment.kt
  app/src/main/java/com/miu/meditationapp/ui/main/LearnViewModel.kt
  app/src/main/res/layout/activity_video.xml
  app/src/main/res/layout/activity_videos_list.xml
  app/src/main/res/layout/fragment_learn.xml
Labels: enhancement

#22 Feature/layout resource
  app/src/main/res/layout/report.xml
Labels: enhancement

#23 Feat/layout: Add report UI in layout resource
  app/src/main/res/layout/report.xml
Labels: enhancement

#27 fix/setup: add missing imports and files
  app/src/main/java/com/miu/meditationapp/MainActivity.kt
  app/src/main/java/com/miu/meditationapp/RecyclerAdapter.kt
  app/src/main/java/com/miu/meditationapp/helper/NotificationReceiver.kt
  app/src/main/java/com/miu/meditationapp/ui/main/ForumFragment.kt
  app/src/main/java/com/miu/meditationapp/ui/main/HomeFragment.kt
  app/src/main/java/com/miu/meditationapp/ui/main/Videos.kt
  app/src/main/java/com/miu/meditationapp/ui/main/VideosView.kt
  app/src/main/res/layout/fragment_home.xml
Labels: bug

#31 style(ui/onboarding): change onboarding images
  app/src/main/java/com/miu/meditationapp/OnboardingActivity.kt
  app/src/main/java/com/miu/meditationapp/RecyclerAdapter.kt
  app/src/main/java/com/miu/meditationapp/ui/main/AboutFragment.kt
  app/src/main/res/drawable/img_book.png
  app/src/main/res/drawable/img_communi.png
  app/src/main/res/drawable/img_medi.png
  app/src/main/res/drawable/img_paint.png
  app/src/main/res/drawable/img_welcome.png
  app/src/main/res/drawable/onboarding_breath.png
  app/src/main/res/drawable/onboarding_community.png
  app/src/main/res/drawable/onboarding_meditation.png
  app/src/main/res/drawable/onboarding_tutorial.png
  app/src/main/res/drawable/onboarding_welcome.png
  app/src/main/res/drawable/view_pager_white.xml
  app/src/main/res/layout/activity_login_forgot_password.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/fragment_about.xml
  app/src/main/res/layout/onboarding_item_container.xml
  app/src/main/res/layout/post_history_items.xml
  app/src/main/res/layout/post_history_items_received.xml
  app/src/main/res/layout/post_history_items_sent.xml
Labels: bug

#32 style(UI/report):change report layout
  app/src/main/res/drawable-v24/check.png
  app/src/main/res/drawable-v24/trophy.png
  app/src/main/res/drawable/check.png
  app/src/main/res/drawable/ic_reminder.png
  app/src/main/res/drawable/trophy.png
  app/src/main/res/font/avenir_font.xml
  app/src/main/res/font/playwrite.ttf
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/report.xml
Labels: enhancement

#34 update homefragment
  app/src/main/java/com/miu/meditationapp/ui/main/HomeFragment.kt
Labels: bug, enhancement

#35 fix/google-signin: fix google sign in option
  app/build.gradle
  app/src/main/java/com/miu/meditationapp/LoginActivity.kt
  app/src/main/res/values/strings.xml
  gradlew
Labels: bug

#36 feature/admin-login: add admin role & realtime user db
  app/src/main/java/com/miu/meditationapp/LoginActivity.kt
  app/src/main/java/com/miu/meditationapp/LoginAddUser.kt
  app/src/main/java/com/miu/meditationapp/models/User.kt
  app/src/main/java/com/miu/meditationapp/ui/main/HomeFragment.kt
Labels: enhancement

#38 style/onboarding-image: Add guiding image on-boarding screen
  app/src/main/java/com/miu/meditationapp/OnboardingActivity.kt
  app/src/main/res/drawable/indicator_inactive_backgound.xml
  app/src/main/res/drawable/onboarding_breath.png
  app/src/main/res/drawable/onboarding_community.png
  app/src/main/res/drawable/onboarding_meditation.png
  app/src/main/res/drawable/onboarding_ready.png
  app/src/main/res/drawable/onboarding_tutorial.png
  app/src/main/res/drawable/view_pager_background.xml
  app/src/main/res/layout/onboarding_item_container.xml
Labels: enhancement

#40 fix/meditation & breath exercise quitting
  app/src/main/java/com/miu/meditationapp/BreathActivity.kt
  app/src/main/java/com/miu/meditationapp/MeditationActivity.kt
Labels: bug

#42 style/forum: change chat layout
  app/src/main/res/drawable/chat_bubble_received.xml
  app/src/main/res/drawable/chat_bubble_sent.xml
  app/src/main/res/drawable/edittext_rounded_shadow.xml
  app/src/main/res/drawable/forum_background.png
  app/src/main/res/drawable/ic_send.png
  app/src/main/res/layout/fragment_forum.xml
Labels: enhancement

#47 style/chat-layout: add username and refine chatting layout
  app/src/main/java/com/miu/meditationapp/adapters/RecyclerAdapter.kt
  app/src/main/res/drawable/chat_bubble_received.xml
  app/src/main/res/drawable/chat_bubble_sent.xml
  app/src/main/res/drawable/edittext_rounded_shadow.xml
  app/src/main/res/layout/fragment_forum.xml
  app/src/main/res/layout/post_history_items_received.xml
  app/src/main/res/layout/post_history_items_sent.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#49 style/auth-style: change styles on auth activities
  app/src/main/res/drawable/auth_background.png
  app/src/main/res/drawable/avatar_select.png
  app/src/main/res/drawable/backup_background.png
  app/src/main/res/drawable/default_song.png
  app/src/main/res/drawable/logo_innermind.png
  app/src/main/res/drawable/mobilebg.jpg
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_login_add_user.xml
  app/src/main/res/layout/activity_login_forgot_password.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/report.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#50 fix/song-menu-popup: change from dialog to popup menu using Android's menu
  app/src/main/java/com/miu/meditationapp/adapters/AdminSongAdapter.kt
  app/src/main/java/com/miu/meditationapp/adapters/ModernSongAdapter.kt
  app/src/main/java/com/miu/meditationapp/fragments/AboutFragment.kt
  app/src/main/java/com/miu/meditationapp/fragments/MusicFragment.kt
  app/src/main/java/com/miu/meditationapp/viewmodels/AboutViewModel.kt
  app/src/main/res/layout/fragment_home.xml
Labels: bug

#53 refactor/music: refactor music feature using hilt (#52)
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/miu/meditationapp/MeditationApp.kt
  app/src/main/java/com/miu/meditationapp/activities/MainActivity.kt
  app/src/main/java/com/miu/meditationapp/adapters/AdminSongAdapter.kt
  app/src/main/java/com/miu/meditationapp/data/repositories/MusicRepository.kt
  app/src/main/java/com/miu/meditationapp/data/repositories/MusicServiceRepository.kt
  app/src/main/java/com/miu/meditationapp/databases/SongDao.kt
  app/src/main/java/com/miu/meditationapp/di/AppModule.kt
  app/src/main/java/com/miu/meditationapp/fragments/AboutFragment.kt
  app/src/main/java/com/miu/meditationapp/fragments/MusicFragment.kt
  app/src/main/java/com/miu/meditationapp/helper/DialogHelper.kt
  app/src/main/java/com/miu/meditationapp/helper/DialogManager.kt
  app/src/main/java/com/miu/meditationapp/helper/DropboxHelper.kt
  app/src/main/java/com/miu/meditationapp/helper/FilePickerHelper.kt
  app/src/main/java/com/miu/meditationapp/helper/MenuHelper.kt
  app/src/main/java/com/miu/meditationapp/helper/MusicStateManager.kt
  app/src/main/java/com/miu/meditationapp/helper/PlaybackManager.kt
  app/src/main/java/com/miu/meditationapp/helper/RecyclerViewManager.kt
  app/src/main/java/com/miu/meditationapp/helper/UploadManager.kt
  app/src/main/java/com/miu/meditationapp/services/AdminSongService.kt
  app/src/main/java/com/miu/meditationapp/services/MusicServiceRefactored.kt
  app/src/main/java/com/miu/meditationapp/viewmodels/MusicViewModel.kt
  app/src/main/res/drawable/logo_innermind.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: enhancement

#54 style/auth-layout: change to tab layout for login and register
  app/schemas/com.miu.meditationapp.databases.MusicDatabase/4.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/miu/meditationapp/MeditationApp.kt
  app/src/main/java/com/miu/meditationapp/activities/LoginActivity.kt
  app/src/main/java/com/miu/meditationapp/activities/LoginAddUser.kt
  app/src/main/java/com/miu/meditationapp/adapters/AuthViewPagerAdapter.kt
  app/src/main/java/com/miu/meditationapp/fragments/AboutFragment.kt
  app/src/main/java/com/miu/meditationapp/fragments/ForumFragment.kt
  app/src/main/java/com/miu/meditationapp/fragments/LoginTabFragment.kt
  app/src/main/java/com/miu/meditationapp/fragments/SignUpTabFragment.kt
  app/src/main/java/com/miu/meditationapp/helper/DialogManager.kt
  app/src/main/java/com/miu/meditationapp/helper/MenuHelper.kt
  app/src/main/java/com/miu/meditationapp/helper/RecyclerViewManager.kt
  app/src/main/res/drawable/ic_more_vert.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_login_add_user.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_sign_up.xml
  app/src/main/res/menu/song_menu_owner.xml
  app/src/main/res/menu/song_menu_viewer.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#56 Fix: Cache admin songs by file name to ensure correct playback
  app/schemas/com.miu.meditationapp.databases.MusicDatabase/3.json
  app/src/main/java/com/miu/meditationapp/adapters/AdminSongAdapter.kt
  app/src/main/java/com/miu/meditationapp/adapters/ModernSongAdapter.kt
  app/src/main/java/com/miu/meditationapp/data/repositories/MusicRepository.kt
  app/src/main/java/com/miu/meditationapp/data/repositories/MusicServiceRepository.kt
  app/src/main/java/com/miu/meditationapp/databases/MusicDatabase.kt
  app/src/main/java/com/miu/meditationapp/databases/SongEntity.kt
  app/src/main/java/com/miu/meditationapp/fragments/MusicFragment.kt
  app/src/main/java/com/miu/meditationapp/helper/DropboxHelper.kt
  app/src/main/java/com/miu/meditationapp/helper/UploadManager.kt
  app/src/main/java/com/miu/meditationapp/services/AdminSongService.kt
  app/src/main/java/com/miu/meditationapp/services/MusicService.kt
  app/src/main/java/com/miu/meditationapp/services/music/MusicPlayer.kt
  app/src/main/java/com/miu/meditationapp/viewmodels/MusicViewModel.kt
  app/src/main/java/com/miu/meditationapp/views/MusicPlayerBarManager.kt
  app/src/main/res/layout/item_admin_song.xml
  app/src/main/res/layout/item_song.xml
  app/src/main/res/layout/music_player_bar.xml
Labels: bug
